### ISSUE TITLE
only +1 for us

### ISSUE THREAD

**Issue by tim-fastpay** [bl00mber/react-phone-input-2#120]
I am getting multiple select options for US. Is there a way I can only have +1 for US?

**Comment by khippert5** [comment]
I currently have the same issue and also have created an issue with a PR to resolve this. Your issue is that you are getting area code with the dial code. The PR I created will resolve this issue once merged. Just waiting for them to merge it: https://github.com/bl00mber/react-phone-input-2/pull/119
