### ISSUE TITLE
Adapt to work on the server

### ISSUE THREAD

**Issue by Alex-ray** [bl00mber/react-phone-input-2#14]
Love the component, I added it to my project; developed it everything worked great.

Until I tried the production build that renders the application on the server (for performance reasons.) The phone input breaks because of two issues.

The first is that `self` is undefined in the [dist/index.js](https://github.com/bl00mber/react-phone-input-2/blob/master/dist/index.js) Maye this is an Uglifyjs/webpack issue?

The second issue is that the global variable `document` is referenced directly. You simply need to check for document before using it.

I did a quick patch on my end and will hopefully get around to a PR soon but no promises.

**Comment by bl00mber** [comment]
Where you want to call `self`? It's not a JS keyword. If you want to add customization to arrow functions, you can call component methods using `this`.
Why `document` should not be referenced directly? It's a common JS API DOM interface.

**Comment by Alex-ray** [comment]
Yes of course, I created a repo here => https://github.com/Alex-ray/react-phone-input-2-ssr-example

You don't want to reference it directly because it will break when its run in other JavaScript environment, such as node in this case.

For example I want to render my webpage on the server before I send it to the client (increase speed, indexing etc...). But because you are referencing DOM specific global variables everything breaks... A simple fix is to check for their existence before using them; does that make sense?

**Comment by bl00mber** [comment]
That's possible it can incorrectly compile for server side because of bugs connected with isomorphic-fetch. https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/79
Also I have no idea how to add event listeners without using reference to `document`. If you have any ideas, would be interesting to consider.

**Comment by jwalton** [comment]
[These references](https://github.com/bl00mber/react-phone-input-2/blob/86de93192847db70647b01110b72653094ccebfc/src/index.js#L167-L168) to `document` are fine, because `componentDidMount()` will never be called server side, but [this bit] should be:

```js
isModernBrowser: (typeof(document) !== 'undefined') &&
    Boolean(document.createElement('input').setSelectionRange),
```

The `typeof` check will make sure `document` is defined before trying to dereference it.

**Comment by jothi-pyt** [comment]
@bl00mber and @Alex-ray Am still facing the issue. When can we expect this to be closed?

**Comment by Alex-ray** [comment]
Hey @jothi-pyt , I do plan on working on this. I planning on carving out some time next week.

Sorry for the delay, I am building a startup and it has been super busy!

**Comment by Alex-ray** [comment]
👆 @bl00mber , @jothi-pyt , @jwalton PR is up and ready to merge!
