### ISSUE TITLE
disableDropdown not working on tab + enter

### ISSUE THREAD

**Issue by tmurph21** [bl00mber/react-phone-input-2#165]
The dropdown is still accessible if you tab into the element and press enter. Only workaround I have found was to set the style on .country-list to display: none;

**Comment by mcaballeropinto** [comment]
I run into the same issue. I thin the problem is that when pressing `TAB` the next element that gets the focus is the `.flag-dropdown`. Since that element has the focus and given this line of code https://github.com/bl00mber/react-phone-input-2/blob/b55da35b83c75ed238e86d0385e01f3cb3743bba/src/index.js#L585, the `showDropdown` state is set to true when 'ENTER' is pressed afterward and the list of countries is displayed.

Another work around is to control the order of the tabs by setting the attribute `tabIndex` to the elements we want to focus on.

I think the right solution that requires code changes is making the element `.flad-dropdown` not selectable when it is not displayed or even not adding it to the DOM at all when `disableDropdown` is set to false.
