### ISSUE TITLE
[BUG]: double country prefix after state update

### ISSUE THREAD

**Issue by mxschmitt** [bl00mber/react-phone-input-2#226]
Minimal reproducible example: https://codesandbox.io/s/nifty-villani-i0428?file=/src/App.js

If value changes from an empty one to a full phone number, the prefix wont get recognised.

**Comment by pietrofxq** [comment]
I am seeing the same issue in my app. The input is receiving a number such as "40752335846" (and I can see this is the value when inspecting the component) but the internal state formattedNumber property duplicates the country prefix:

![image](https://user-images.githubusercontent.com/6238029/80527423-b6861280-896a-11ea-927b-1631252d9e9f.png)

**Comment by DanielOlarte** [comment]
We are having the same issue in our app, any news on the PR? Thanks!

**Comment by urre** [comment]
Same here. Any workarounds?

**Comment by pietrofxq** [comment]
@urre You can revert back to 2.9.5

**Comment by sedenardi** [comment]
Seems like the problem lies https://github.com/bl00mber/react-phone-input-2/blob/master/src/index.js#L316 where if the incoming value has a prefix it fails the `startsWith(value, selectedCountry.dialCode)` check. 

In your codesandbox example, if I pass in the US phone number `+1 (212) 555-1234` it gets formatted to `+1 (121) 255-5123`, but if I pass in `1 (212) 555-1234` it gets correctly formatted to `+1 (212) 555-1234`.

**Comment by sedenardi** [comment]
Thanks @bl00mber!

**Comment by sadux** [comment]
Thank you very much @bl00mber!
You made my day!

**Comment by nguyenkhoadang** [comment]
<img width="633" alt="Screenshot 2024-06-15 at 12 55 40" src="https://github.com/bl00mber/react-phone-input-2/assets/52766534/ecb6c1ad-5062-4ea6-8f86-05cf6e876b72">


I still get this error in 2.15.1. Any workarounds?

im input +8433872xxxx ==> it show 848433872xxxx
