### ISSUE TITLE
Country code selector screenreader accessibility

### ISSUE THREAD

**Issue by sackeyjason** [bl00mber/react-phone-input-2#250]
I've been working on this, and intend to put forward a pull request.

As it stands, you can't navigate the country code dropdown list as a blind screenreader user. The list items are all smooshed together because of the role="button" attribute on the ancestor.

So I suggest:

- move that role attribute down to the 'selected-flag' div
- add extra attributes to make it function more like a native select element:
  - add 'listbox' and 'option' roles, plus the `aria-selected="true"` attribute
  - example here: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
  - but don't worry about `aria-activedescendant` (trickier to implement and, in my testing, unnecessary)

**Comment by bl00mber** [comment]
Please send PR if you want to suggest a change or a fix but make sure that it will not break existing functionality!

**Comment by Vanals** [comment]
I Still find it impossible to navigate through the dropdown with Safari + Voiceover.

It read all the country in one go and the tabs button does not let you move you down.  Nor the country are being read by the SR.

It does not replicate the native select input behaviour. Not sure the fix is working?
<img width="947" alt="Screenshot 2021-05-25 at 17 43 02" src="https://user-images.githubusercontent.com/25549355/119536185-b3816f80-bd80-11eb-83e4-f1a086ccec20.png">
